services:
  inference:
    build:
      context: .
      dockerfile: Dockerfile.infer
      provenance: false
      sbom: false
    container_name: amazon-inference
    ports:
      - "8001:8001"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      provenance: false
      sbom: false
    container_name: amazon-web
    environment:
      - INFERENCE_URL=http://inference:8001
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - inference
    restart: unless-stopped